// components/ui/ExportBar.tsx
// Phase 17 — Export as PDF / Download JSON feature.

'use client';
import { Download, FileText, FileJson } from 'lucide-react';

interface ExportBarProps {
    ticker: string;
    data: unknown;
}

function exportJSON(ticker: string, data: unknown) {
    const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${ticker}_analysis_${new Date().toISOString().slice(0, 10)}.json`;
    a.click();
    URL.revokeObjectURL(url);
}

async function exportPDF(ticker: string) {
    // Use browser print dialog with a print-styled view
    const printContent = document.getElementById('analysis-root');
    if (!printContent) { window.print(); return; }
    const w = window.open('', '_blank');
    if (!w) { window.print(); return; }
    w.document.write(`
        <html>
        <head>
            <title>${ticker} — Financial Research Memo</title>
            <style>
                body { font-family: Inter, system-ui, sans-serif; color: #111; padding: 32px; max-width: 900px; margin: auto; }
                h1 { font-size: 22px; margin-bottom: 4px; }
                h2 { font-size: 16px; margin-top: 20px; border-bottom: 1px solid #eee; padding-bottom: 6px; }
                p, li { font-size: 13px; line-height: 1.6; color: #333; }
                .meta { font-size: 11px; color: #888; margin-bottom: 24px; }
                @media print { body { padding: 16px; } }
            </style>
        </head>
        <body>
            <h1>${ticker} — Financial Research Report</h1>
            <p class="meta">Generated by AI Financial Research Agent · ${new Date().toLocaleString()}</p>
            ${printContent.innerHTML}
        </body>
        </html>
    `);
    w.document.close();
    setTimeout(() => { w.print(); }, 500);
}

export default function ExportBar({ ticker, data }: ExportBarProps) {
    const apiBase = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:8000/api/v1';
    const docsUrl = apiBase.replace('/api/v1', '') + '/docs';

    return (
        <div className="flex items-center gap-2 fade-in">
            <span className="text-[11px] font-semibold mr-1" style={{ color: 'var(--text-muted)' }}>Export:</span>
            <button className="btn-export" onClick={() => exportPDF(ticker)}>
                <FileText size={13} /> PDF Memo
            </button>
            <button className="btn-export" onClick={() => exportJSON(ticker, data)}>
                <FileJson size={13} /> JSON Data
            </button>
            <a
                href={docsUrl}
                target="_blank"
                rel="noopener noreferrer"
                className="btn-export"
            >
                <Download size={13} /> API Docs
            </a>
        </div>
    );
}
