"""
schemas/risk.py — Pydantic models for the Risk Intelligence Engine (Phase 6).
"""

from datetime import datetime
from typing import List, Optional
from pydantic import BaseModel, ConfigDict


class RiskComponent(BaseModel):
    score: float       # 0 to 100 (where 100 is MAX RISK)
    level: str         # "low", "moderate", "high"
    explanation: str


class HiddenRisk(BaseModel):
    risk_name: str
    severity: str      # "moderate", "high", "critical"
    explanation: str


class RiskResponse(BaseModel):
    """
    Structured composite risk profile generated by the Risk Intelligence Engine.
    Combines backward-looking fundamentals with statistical volatility.
    """
    ticker: str
    
    composite_risk_score: float    # 0 to 100 (100 = MAX RISK)
    risk_level: str                # "low", "moderate", "high"
    
    leverage_risk: RiskComponent
    liquidity_risk: RiskComponent
    earnings_risk: RiskComponent
    cashflow_risk: RiskComponent
    
    hidden_risks: List[HiddenRisk]
    macro_sensitivity_notes: str
    
    based_on_years: int
    generated_at: datetime
    
    model_config = ConfigDict(from_attributes=True)
